# additional data require to create the Docker image
packaging:
  # files to add to the build, usually used with ADD in the Dockerfile
  add:
    # the plugin always filters
    - target/${project.build.finalName}.jar
    - hello-world.yml
# optional list of port to expose on the host
ports:
  - 8080
# containers that this should be linked to, started before this one and stopped afterwards
links:
  - mysql
healthChecks:
  pings:
    - url: http://localhost:8080/hello-world
      timeout: 60000
tag: alex.e.c/${project.artifactId}-app:${project.version}